export const ErrorCodes = {
  // Auth
  MISSING_API_KEY: 'MISSING_API_KEY',
  INVALID_API_KEY: 'INVALID_API_KEY',
  API_KEY_REVOKED: 'API_KEY_REVOKED',
  API_KEY_EXPIRED: 'API_KEY_EXPIRED',
  INVALID_ADMIN_SECRET: 'INVALID_ADMIN_SECRET',
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_RULE_SET: 'INVALID_RULE_SET',
  // Business
  BUSINESS_NOT_FOUND: 'BUSINESS_NOT_FOUND',
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  // Customer
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  // Account
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  ACCOUNT_NOT_ACTIVE: 'ACCOUNT_NOT_ACTIVE',
  ACCOUNT_ALREADY_CLOSED: 'ACCOUNT_ALREADY_CLOSED',
  ACCOUNT_TERMINAL_STATE: 'ACCOUNT_TERMINAL_STATE',
  DUPLICATE_ACCOUNT_REF: 'DUPLICATE_ACCOUNT_REF',
  // Rules
  RULE_NOT_FOUND: 'RULE_NOT_FOUND',
  RULE_CONFLICT: 'RULE_CONFLICT',
  PERCENTAGE_SUM_EXCEEDS_100: 'PERCENTAGE_SUM_EXCEEDS_100',
  // Treasury
  INSUFFICIENT_BUCKET_BALANCE: 'INSUFFICIENT_BUCKET_BALANCE',
  BUCKET_NOT_FOUND: 'BUCKET_NOT_FOUND',
  // Demo
  DEMO_MODE_ONLY: 'DEMO_MODE_ONLY',
  // Nomba
  NOMBA_API_ERROR: 'NOMBA_API_ERROR',
  INVALID_WEBHOOK_SIGNATURE: 'INVALID_WEBHOOK_SIGNATURE',
  // Idempotency
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
